### PR TITLE
add yarn. get change PropTypes import to ready for react16.

### PR DESCRIPTION
**Pull request by ericdfields**
Mostly wanted to get PropTypes moved over to prop-types package. How do you feel about yarn?

### CODE REVIEW

**Comment by danott** [comment]
@ericdfields Thanks for opening this. I _think_ I  see three separate changes going on here?

1. Moving `PropTypes` over to the `prop-types` package in preparation for React 16
2. Using `yarn` to manage dependencies
3. Using `prettier` to format code consistently

Does that sound right?

I support all these changes to the project. I _feel_ like it might be more helpful to have each change take place in a separate commit, so historically we see what shift-in-ideals lead to changes-in-code?

**Comment by ericdfields** [comment]
I’m not sure if I meant to include prettier, but I can walk these back and put them up as individual PRs for sure.

**Comment by zernie** [comment]
Would be great to see this merged, even if commit history is a bit of a mess.

**Comment by ericdfields** [comment]
What would improve it? Should I make the same changes and then rebase? 

I don’t contribute much to open source, so my usual git flow is

* branch
* make changes, commit as necessary
* PR or merge to master, depending on size of changes

I’d be open to reworking these changes.

**Pull request closed without merging**
